name: Build and Deploy Multilingual App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Permet de lancer le workflow manuellement depuis l'interface GitHub
  workflow_dispatch:

permissions:
  contents: write

jobs:
  i18n-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Étape 1: Extraction des traductions avec format spécifié
      - name: Extract i18n messages
        run: npx ng extract-i18n --output-path src/locale --format=xlf

      # Étape 2: Upload des fichiers de traduction
      - name: Upload translations
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        env:
          LOKALISE_API_KEY: '7cd9343a4ee5bd6c3d2066f4cc9eedc8e6de6388'
        run: node upload-translations.js

      # Étape 3: Download des traductions mises à jour
      - name: Download translations
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        env:
          LOKALISE_API_KEY: '7cd9343a4ee5bd6c3d2066f4cc9eedc8e6de6388'
        run: node download-translations.js

      # Étape 4: Commit des nouvelles traductions si elles ont changé
      - name: Commit updated translations
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/locale/*.xlf
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update translations" && git push)

      # Étape 5: Build de l'application avec toutes les langues
      - name: Build multilingual app
        run: npx ng build --localize --configuration=production --base-href=/angular-todo-app/

      # Étape 6: Créer le fichier 404.html
      - name: Create 404.html
        run: |
          cd dist/angular-todo-app/browser
          cp index.html 404.html

      # Étape 7: Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-todo-app/browser
          enable_jekyll: false
          allow_empty_commit: true
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
