name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Automated Translations"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm ci --legacy-peer-deps
          npm install angular-cli-ghpages --save-dev
          
      - name: Build for all languages
        run: |
          # Build French version (default)
          ng build --configuration=production --base-href="/angular-todo-app/"
          
          # Build English version
          ng build --configuration=production,en --base-href="/angular-todo-app/en/" --output-path=dist/en
          
          # Build Arabic version
          ng build --configuration=production,ar --base-href="/angular-todo-app/ar/" --output-path=dist/ar
          
          # Create language switcher script
          echo "const userLang = navigator.language || navigator.userLanguage;
          let redirectPath = '/angular-todo-app/';
          if (userLang.startsWith('en')) {
            redirectPath += 'en/';
          } else if (userLang.startsWith('ar')) {
            redirectPath += 'ar/';
          }
          window.location.href = redirectPath;" > dist/redirect.js
          
          # Create index.html for language redirection
          echo "<!DOCTYPE html>
          <html>
            <head>
              <meta charset='utf-8'>
              <title>Todo App</title>
              <script src='redirect.js'></script>
            </head>
            <body>
              <p>Redirecting to your preferred language...</p>
            </body>
          </html>" > dist/index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
