name: Build and Deploy

on:
  workflow_run:
    workflows: ["Automated Translations"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Cache npm dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g @angular/cli
          npm install -g angular-cli-ghpages
          
      - name: Build for all languages
        run: |
          # Build French version (default)
          ng build --configuration=production --base-href="https://souakli.github.io/angular-todo-app/"
          
          # Build English version
          ng build --configuration=production,en --base-href="https://souakli.github.io/angular-todo-app/en/" --output-path=dist/en
          
          # Build Arabic version
          ng build --configuration=production,ar --base-href="https://souakli.github.io/angular-todo-app/ar/" --output-path=dist/ar
          
          # Create language switcher script
          echo "const userLang = navigator.language || navigator.userLanguage;
          let redirectPath = 'https://souakli.github.io/angular-todo-app/';
          if (userLang.startsWith('en')) {
            redirectPath += 'en/';
          } else if (userLang.startsWith('ar')) {
            redirectPath += 'ar/';
          }
          window.location.href = redirectPath;" > dist/redirect.js
          
          # Create index.html for language redirection
          echo "<!DOCTYPE html>
          <html>
            <head>
              <meta charset='utf-8'>
              <title>Todo App</title>
              <script src='redirect.js'></script>
            </head>
            <body>
              <p>Redirecting to your preferred language...</p>
            </body>
          </html>" > dist/index.html
          
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          npx angular-cli-ghpages --dir=dist --repo=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --name="${{ github.actor }}" --email="${{ github.actor }}@users.noreply.github.com" --branch=gh-pages --no-silent
