name: Automated Translations

on:
  push:
    branches:
      - main

jobs:
  update-translations:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm ci --legacy-peer-deps
          npm install @lokalise/node-api unzipper --legacy-peer-deps
        
      - name: Extract i18n strings
        run: |
          npm run i18n:extract
          dir src\locale
        shell: cmd
        
      - name: Upload to Lokalise
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          node upload-translations.js
        shell: pwsh
        
      - name: Wait for translations (2 minutes)
        run: Start-Sleep -Seconds 120
        shell: pwsh
        
      - name: Download translations
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          node download-translations.js
        shell: pwsh
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update translations'
          title: 'Update translations'
          body: |
            Automated translation update from Lokalise
            - Extracted new strings
            - Updated translations for all languages
          branch: update-translations
          base: main
