name: Automated Translations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli
          
      - name: Extract messages
        run: |
          ng extract-i18n --output-path src/locale
          
      - name: Upload translations
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          node upload-translations.js
          
      - name: Download translations
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          node download-translations.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/locale/*
          git commit -m "chore: update translations" || echo "No changes to commit"
          git push origin main
